<?php require_once 'config.php'; $pageTitle='Analytics'; $pageDescription='Tableau de bord et statistiques'; ?>
<!DOCTYPE html><html lang="fr"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>NEXUS • Analytics</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><script src="https://cdn.tailwindcss.com"></script><script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.1/dist/chart.umd.min.js"></script><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css">
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=Orbitron:wght@400;500;600;700;800&display=swap" rel="stylesheet">
<style>:root{--neon-cyan:#00f5ff;--neon-purple:#c026d3;--dark-bg:#0a0a0f}body{background:radial-gradient(circle at 50% 20%,rgba(34,211,238,0.15) 0%,transparent 60%),linear-gradient(135deg,#0a0a0f 0%,#1a0a2e 100%);color:#e0f2fe;font-family:'Inter',sans-serif;min-height:100vh}.title-font{font-family:'Orbitron',sans-serif}.neon-text{text-shadow:0 0 15px var(--neon-cyan),0 0 30px var(--neon-cyan)}.glass-panel{background:rgba(15,23,42,0.85);backdrop-filter:blur(24px);border:1px solid rgba(34,211,238,0.3);border-radius:24px}.btn-neon{background:linear-gradient(135deg,var(--neon-cyan),var(--neon-purple));color:#000;font-weight:700;border:none;transition:all 0.3s ease}.nav-link{color:#94a3b8!important;transition:all 0.3s ease}.nav-link:hover,.nav-link.active{color:var(--neon-cyan)!important}.sidebar{width:280px;position:fixed;left:0;top:0;height:100vh;overflow-y:auto;z-index:1000}.main-content{margin-left:280px;min-height:100vh}::-webkit-scrollbar{width:8px}::-webkit-scrollbar-track{background:var(--dark-bg)}::-webkit-scrollbar-thumb{background:linear-gradient(180deg,var(--neon-cyan),var(--neon-purple));border-radius:4px}.stat-card{background:linear-gradient(135deg,rgba(34,211,238,0.1),rgba(192,38,211,0.1));border:1px solid rgba(34,211,238,0.2);border-radius:20px;padding:1.5rem;transition:all 0.3s ease}.stat-card:hover{transform:scale(1.05);border-color:var(--neon-cyan);box-shadow:0 0 40px rgba(34,211,238,0.3)}</style></head><body>
<?php if(!$is_logged):header("Location:index.php");exit;endif;?>
<nav class="sidebar glass-panel border-r border-cyan-400/30"><div class="p-8 border-b border-cyan-400/20"><h1 class="text-5xl font-bold title-font neon-text tracking-tighter">NEXUS</h1><div class="flex items-center gap-3 mt-4"><div class="w-3 h-3 bg-emerald-400 rounded-full animate-pulse"></div><span class="text-emerald-400 text-xs font-medium tracking-widest">EN LIGNE</span></div></div><div class="p-6 border-b border-cyan-400/20"><div class="flex items-center gap-3 mb-3"><div class="w-12 h-12 rounded-full bg-gradient-to-br from-cyan-400 to-purple-500 flex items-center justify-center text-black font-bold text-lg"><?=strtoupper(substr($_SESSION['email'],0,1))?></div><div><p class="text-cyan-300 font-medium text-sm"><?=htmlspecialchars($_SESSION['email'])?></p><p class="text-slate-400 text-xs">Utilisateur Neural</p></div></div></div><div class="p-4"><ul class="space-y-1"><li><a href="index.php" class="nav-link d-flex align-items-center gap-3 px-4 py-3 rounded-xl"><i class="fa-solid fa-comments text-xl text-cyan-400"></i><span>Dialogue</span></a></li><li><a href="profile.php" class="nav-link d-flex align-items-center gap-3 px-4 py-3 rounded-xl"><i class="fa-solid fa-brain text-xl text-purple-400"></i><span>Profil Neuro</span></a></li><li><a href="projects.php" class="nav-link d-flex align-items-center gap-3 px-4 py-3 rounded-xl"><i class="fa-solid fa-folder-open text-xl text-green-400"></i><span>Projets</span></a></li><li><a href="notes.php" class="nav-link d-flex align-items-center gap-3 px-4 py-3 rounded-xl"><i class="fa-solid fa-note-sticky text-xl text-yellow-400"></i><span>Notes</span></a></li><li><a href="analytics.php" class="nav-link active d-flex align-items-center gap-3 px-4 py-3 rounded-xl"><i class="fa-solid fa-chart-line text-xl text-blue-400"></i><span>Analytics</span></a></li><li><a href="settings.php" class="nav-link d-flex align-items-center gap-3 px-4 py-3 rounded-xl"><i class="fa-solid fa-gear text-xl text-orange-400"></i><span>Paramètres</span></a></li></ul></div><div class="p-6 border-t border-cyan-400/20 mt-auto"><a href="?logout=1" class="d-flex align-items-center gap-3 text-red-400 hover:text-red-300 transition-colors px-4 py-3"><i class="fa-solid fa-power-off"></i><span>DÉCONNEXION</span></a></div></nav>
<main class="main-content"><header class="glass-panel mx-4 mt-4 p-6 flex items-center justify-between"><div><h2 class="text-3xl font-bold title-font text-gradient"><?=$pageTitle?></h2><p class="text-slate-400 text-sm mt-1"><?=$pageDescription?></p></div></header><div class="p-6">
<div class="grid grid-cols-1 md:grid-cols-4 gap-6 mb-6">
<div class="stat-card text-center"><i class="fa-solid fa-comments text-4xl text-cyan-400 mb-3"></i><div class="text-3xl font-bold text-cyan-300" id="stat-msgs">0</div><div class="text-slate-400 text-sm">Messages</div></div>
<div class="stat-card text-center"><i class="fa-solid fa-folder-open text-4xl text-green-400 mb-3"></i><div class="text-3xl font-bold text-green-300" id="stat-proj">0</div><div class="text-slate-400 text-sm">Projets</div></div>
<div class="stat-card text-center"><i class="fa-solid fa-note-sticky text-4xl text-yellow-400 mb-3"></i><div class="text-3xl font-bold text-yellow-300" id="stat-notes">0</div><div class="text-slate-400 text-sm">Notes</div></div>
<div class="stat-card text-center"><i class="fa-solid fa-brain text-4xl text-purple-400 mb-3"></i><div class="text-3xl font-bold text-purple-300" id="stat-level">1</div><div class="text-slate-400 text-sm">Niveau</div></div>
</div>
<div class="grid grid-cols-1 lg:grid-cols-2 gap-6"><div class="glass-panel p-8"><h3 class="text-xl font-bold title-font mb-6 text-cyan-300"><i class="fa-solid fa-chart-pie me-2"></i>Répartition</h3><canvas id="pieChart" height="250"></canvas></div><div class="glass-panel p-8"><h3 class="text-xl font-bold title-font mb-6 text-purple-300"><i class="fa-solid fa-chart-bar me-2"></i>Activité</h3><canvas id="barChart" height="250"></canvas></div></div>
</div></main>
<script>
async function loadStats(){try{const res=await fetch('api.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'action=get_stats'});const data=await res.json();if(data.success){document.getElementById('stat-msgs').textContent=data.stats.messages;document.getElementById('stat-proj').textContent=data.stats.projects;document.getElementById('stat-notes').textContent=data.stats.notes;document.getElementById('stat-level').textContent=data.user.level||1;new Chart(document.getElementById('pieChart'),{type:'doughnut',data:{labels:['Messages','Projets','Notes'],datasets:[{data:[data.stats.messages,data.stats.projects,data.stats.notes],backgroundColor:['#22d3ee','#10b981','#fbbf24'],borderWidth:0}]},options:{plugins:{legend:{position:'bottom',labels:{color:'#e0f2fe'}}}}});new Chart(document.getElementById('barChart'),{type:'bar',data:{labels:['Messages','Projets','Notes','Niveau'],datasets:[{label:'Statistiques',data:[data.stats.messages,data.stats.projects,data.stats.notes,data.user.level||1],backgroundColor:['#22d3ee','#10b981','#fbbf24','#c026d3'],borderRadius:8}]},options:{scales:{y:{beginAtZero:true,ticks:{color:'#94a3b8'},grid:{color:'rgba(148,163,184,0.1)'}},x:{ticks:{color:'#94a3b8'},grid:{display:false}}},plugins:{legend:{display:false}}}});}}catch(e){console.error(e);}}
document.addEventListener('DOMContentLoaded',loadStats);
</script></body></html>
