<?php require_once 'config.php'; $pageTitle='Notes'; $pageDescription='Base de connaissances personnelle'; ?>
<!DOCTYPE html><html lang="fr"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>NEXUS • Notes</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><script src="https://cdn.tailwindcss.com"></script><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css">
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=Orbitron:wght@400;500;600;700;800&display=swap" rel="stylesheet">
<style>:root{--neon-cyan:#00f5ff;--neon-purple:#c026d3;--dark-bg:#0a0a0f}body{background:radial-gradient(circle at 50% 20%,rgba(34,211,238,0.15) 0%,transparent 60%),linear-gradient(135deg,#0a0a0f 0%,#1a0a2e 100%);color:#e0f2fe;font-family:'Inter',sans-serif;min-height:100vh}.title-font{font-family:'Orbitron',sans-serif}.neon-text{text-shadow:0 0 15px var(--neon-cyan),0 0 30px var(--neon-cyan)}.glass-panel{background:rgba(15,23,42,0.85);backdrop-filter:blur(24px);border:1px solid rgba(34,211,238,0.3);border-radius:24px}.btn-neon{background:linear-gradient(135deg,var(--neon-cyan),var(--neon-purple));color:#000;font-weight:700;border:none;transition:all 0.3s ease}.nav-link{color:#94a3b8!important;transition:all 0.3s ease}.nav-link:hover,.nav-link.active{color:var(--neon-cyan)!important}.sidebar{width:280px;position:fixed;left:0;top:0;height:100vh;overflow-y:auto;z-index:1000}.main-content{margin-left:280px;min-height:100vh}::-webkit-scrollbar{width:8px}::-webkit-scrollbar-track{background:var(--dark-bg)}::-webkit-scrollbar-thumb{background:linear-gradient(180deg,var(--neon-cyan),var(--neon-purple));border-radius:4px}.note-card{background:rgba(30,41,59,0.6);border:1px solid rgba(103,232,249,0.2);border-radius:16px;padding:1.5rem;transition:all 0.3s ease}.note-card:hover{border-color:var(--neon-cyan);box-shadow:0 0 30px rgba(34,211,238,0.3)}.input-neon{background:rgba(2,6,23,0.8);border:1px solid rgba(34,211,238,0.3);color:#e0f2fe}.input-neon:focus{outline:none;border-color:var(--neon-cyan);box-shadow:0 0 20px rgba(34,211,238,0.3)}</style></head><body>
<?php if(!$is_logged):header("Location:index.php");exit;endif;?>
<nav class="sidebar glass-panel border-r border-cyan-400/30"><div class="p-8 border-b border-cyan-400/20"><h1 class="text-5xl font-bold title-font neon-text tracking-tighter">NEXUS</h1><div class="flex items-center gap-3 mt-4"><div class="w-3 h-3 bg-emerald-400 rounded-full animate-pulse"></div><span class="text-emerald-400 text-xs font-medium tracking-widest">EN LIGNE</span></div></div><div class="p-6 border-b border-cyan-400/20"><div class="flex items-center gap-3 mb-3"><div class="w-12 h-12 rounded-full bg-gradient-to-br from-cyan-400 to-purple-500 flex items-center justify-center text-black font-bold text-lg"><?=strtoupper(substr($_SESSION['email'],0,1))?></div><div><p class="text-cyan-300 font-medium text-sm"><?=htmlspecialchars($_SESSION['email'])?></p><p class="text-slate-400 text-xs">Utilisateur Neural</p></div></div></div><div class="p-4"><ul class="space-y-1"><li><a href="index.php" class="nav-link d-flex align-items-center gap-3 px-4 py-3 rounded-xl"><i class="fa-solid fa-comments text-xl text-cyan-400"></i><span>Dialogue</span></a></li><li><a href="profile.php" class="nav-link d-flex align-items-center gap-3 px-4 py-3 rounded-xl"><i class="fa-solid fa-brain text-xl text-purple-400"></i><span>Profil Neuro</span></a></li><li><a href="projects.php" class="nav-link d-flex align-items-center gap-3 px-4 py-3 rounded-xl"><i class="fa-solid fa-folder-open text-xl text-green-400"></i><span>Projets</span></a></li><li><a href="notes.php" class="nav-link active d-flex align-items-center gap-3 px-4 py-3 rounded-xl"><i class="fa-solid fa-note-sticky text-xl text-yellow-400"></i><span>Notes</span></a></li><li><a href="analytics.php" class="nav-link d-flex align-items-center gap-3 px-4 py-3 rounded-xl"><i class="fa-solid fa-chart-line text-xl text-blue-400"></i><span>Analytics</span></a></li><li><a href="settings.php" class="nav-link d-flex align-items-center gap-3 px-4 py-3 rounded-xl"><i class="fa-solid fa-gear text-xl text-orange-400"></i><span>Paramètres</span></a></li></ul></div><div class="p-6 border-t border-cyan-400/20 mt-auto"><a href="?logout=1" class="d-flex align-items-center gap-3 text-red-400 hover:text-red-300 transition-colors px-4 py-3"><i class="fa-solid fa-power-off"></i><span>DÉCONNEXION</span></a></div></nav>
<main class="main-content"><header class="glass-panel mx-4 mt-4 p-6 flex items-center justify-between"><div><h2 class="text-3xl font-bold title-font text-gradient"><?=$pageTitle?></h2><p class="text-slate-400 text-sm mt-1"><?=$pageDescription?></p></div><button onclick="showModal()" class="btn-neon px-6 py-3 rounded-xl"><i class="fa-solid fa-plus me-2"></i>Nouvelle Note</button></header><div class="p-6"><div id="notes-grid" class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6"></div></div></main>

<div id="noteModal" class="modal fixed inset-0 bg-black/80 backdrop-blur-sm z-50 hidden"><div class="flex items-center justify-center min-h-screen p-6"><div class="glass-panel max-w-lg w-full p-8 rounded-3xl border border-cyan-400/30"><h3 class="text-2xl font-bold title-font mb-6 text-cyan-300">Nouvelle Note</h3><form id="noteForm"><div class="mb-4"><label class="text-cyan-300 text-sm mb-2 block">Titre</label><input type="text" id="noteTitle" required class="w-full input-neon rounded-xl px-4 py-3"></div><div class="mb-4"><label class="text-cyan-300 text-sm mb-2 block">Contenu</label><textarea id="noteContent" rows="5" class="w-full input-neon rounded-xl px-4 py-3"></textarea></div><div class="mb-4"><label class="text-cyan-300 text-sm mb-2 block">Tags (séparés par virgules)</label><input type="text" id="noteTags" placeholder="ia, projet, idee" class="w-full input-neon rounded-xl px-4 py-3"></div><div class="mb-6"><label class="text-cyan-300 text-sm mb-2 block">Catégorie</label><select id="noteCategory" class="w-full input-neon rounded-xl px-4 py-3"><option value="general">Général</option><option value="work">Travail</option><option value="personal">Personnel</option><option value="ideas">Idées</option><option value="research">Recherche</option></select></div><div class="flex gap-3"><button type="submit" class="btn-neon flex-1 py-3 rounded-xl">Créer</button><button type="button" onclick="hideModal()" class="px-6 py-3 rounded-xl border border-slate-600 text-slate-300 hover:border-slate-400">Annuler</button></div></form></div></div></div>

<script>
async function loadNotes(){try{const res=await fetch('api.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'action=get_notes'});const data=await res.json();const grid=document.getElementById('notes-grid');if(data.notes.length===0){grid.innerHTML='<div class="col-span-full text-center text-slate-400 py-12"><i class="fa-solid fa-note-sticky text-6xl mb-4 opacity-30"></i><p>Aucune note. Capturez vos premières idées !</p></div>';return;}grid.innerHTML=data.notes.map(n=>`<div class="note-card"><div class="flex items-start justify-between mb-3"><div><h4 class="font-bold text-lg text-cyan-300">${escapeHtml(n.title)}</h4><span class="text-xs text-slate-500">${new Date(n.created_at).toLocaleDateString('fr-FR')}</span></div><span class="px-3 py-1 rounded-full text-xs bg-cyan-500/20 text-cyan-300">${n.category}</span></div><p class="text-slate-300 text-sm mb-4 line-clamp-3">${escapeHtml(n.content||'')}</p>${n.tags?`<div class="flex flex-wrap gap-2 mb-3">${n.tags.split(',').map(t=>`<span class="text-xs px-2 py-1 rounded bg-slate-700 text-slate-300">${escapeHtml(t.trim())}</span>`).join('')}</div>`:''}<div class="flex justify-end"><button onclick="deleteNote(${n.id})" class="p-2 rounded-lg bg-red-500/20 text-red-300 hover:bg-red-500/30"><i class="fa-solid fa-trash"></i></button></div></div>`).join('');}catch(e){console.error(e);}}
function showModal(){document.getElementById('noteModal').classList.remove('hidden');}
function hideModal(){document.getElementById('noteModal').classList.add('hidden');}
document.getElementById('noteForm').addEventListener('submit',async(e)=>{e.preventDefault();const formData=new URLSearchParams();formData.append('action','save_note');formData.append('title',document.getElementById('noteTitle').value);formData.append('content',document.getElementById('noteContent').value);formData.append('tags',document.getElementById('noteTags').value);formData.append('category',document.getElementById('noteCategory').value);await fetch('api.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:formData});hideModal();loadNotes();});
async function deleteNote(id){if(confirm('Supprimer cette note ?')){await fetch('api.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:`action=delete_note&id=${id}`});loadNotes();}}
function escapeHtml(t){const d=document.createElement('div');d.textContent=t;return d.innerHTML;}
document.addEventListener('DOMContentLoaded',loadNotes);
</script></body></html>
