<?php require_once 'config.php'; $pageTitle='Paramètres'; $pageDescription='Configuration de votre espace'; ?>
<!DOCTYPE html><html lang="fr"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>NEXUS • Paramètres</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><script src="https://cdn.tailwindcss.com"></script><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css">
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=Orbitron:wght@400;500;600;700;800&display=swap" rel="stylesheet">
<style>:root{--neon-cyan:#00f5ff;--neon-purple:#c026d3;--dark-bg:#0a0a0f}body{background:radial-gradient(circle at 50% 20%,rgba(34,211,238,0.15) 0%,transparent 60%),linear-gradient(135deg,#0a0a0f 0%,#1a0a2e 100%);color:#e0f2fe;font-family:'Inter',sans-serif;min-height:100vh}.title-font{font-family:'Orbitron',sans-serif}.neon-text{text-shadow:0 0 15px var(--neon-cyan),0 0 30px var(--neon-cyan)}.glass-panel{background:rgba(15,23,42,0.85);backdrop-filter:blur(24px);border:1px solid rgba(34,211,238,0.3);border-radius:24px}.btn-neon{background:linear-gradient(135deg,var(--neon-cyan),var(--neon-purple));color:#000;font-weight:700;border:none;transition:all 0.3s ease}.nav-link{color:#94a3b8!important;transition:all 0.3s ease}.nav-link:hover,.nav-link.active{color:var(--neon-cyan)!important}.sidebar{width:280px;position:fixed;left:0;top:0;height:100vh;overflow-y:auto;z-index:1000}.main-content{margin-left:280px;min-height:100vh}::-webkit-scrollbar{width:8px}::-webkit-scrollbar-track{background:var(--dark-bg)}::-webkit-scrollbar-thumb{background:linear-gradient(180deg,var(--neon-cyan),var(--neon-purple));border-radius:4px}.input-neon{background:rgba(2,6,23,0.8);border:1px solid rgba(34,211,238,0.3);color:#e0f2fe}.input-neon:focus{outline:none;border-color:var(--neon-cyan);box-shadow:0 0 20px rgba(34,211,238,0.3)}.setting-card{background:rgba(30,41,59,0.6);border:1px solid rgba(103,232,249,0.2);border-radius:16px;padding:1.5rem}</style></head><body>
<?php if(!$is_logged):header("Location:index.php");exit;endif;?>
<nav class="sidebar glass-panel border-r border-cyan-400/30"><div class="p-8 border-b border-cyan-400/20"><h1 class="text-5xl font-bold title-font neon-text tracking-tighter">NEXUS</h1><div class="flex items-center gap-3 mt-4"><div class="w-3 h-3 bg-emerald-400 rounded-full animate-pulse"></div><span class="text-emerald-400 text-xs font-medium tracking-widest">EN LIGNE</span></div></div><div class="p-6 border-b border-cyan-400/20"><div class="flex items-center gap-3 mb-3"><div class="w-12 h-12 rounded-full bg-gradient-to-br from-cyan-400 to-purple-500 flex items-center justify-center text-black font-bold text-lg"><?=strtoupper(substr($_SESSION['email'],0,1))?></div><div><p class="text-cyan-300 font-medium text-sm"><?=htmlspecialchars($_SESSION['email'])?></p><p class="text-slate-400 text-xs">Utilisateur Neural</p></div></div></div><div class="p-4"><ul class="space-y-1"><li><a href="index.php" class="nav-link d-flex align-items-center gap-3 px-4 py-3 rounded-xl"><i class="fa-solid fa-comments text-xl text-cyan-400"></i><span>Dialogue</span></a></li><li><a href="profile.php" class="nav-link d-flex align-items-center gap-3 px-4 py-3 rounded-xl"><i class="fa-solid fa-brain text-xl text-purple-400"></i><span>Profil Neuro</span></a></li><li><a href="projects.php" class="nav-link d-flex align-items-center gap-3 px-4 py-3 rounded-xl"><i class="fa-solid fa-folder-open text-xl text-green-400"></i><span>Projets</span></a></li><li><a href="notes.php" class="nav-link d-flex align-items-center gap-3 px-4 py-3 rounded-xl"><i class="fa-solid fa-note-sticky text-xl text-yellow-400"></i><span>Notes</span></a></li><li><a href="analytics.php" class="nav-link d-flex align-items-center gap-3 px-4 py-3 rounded-xl"><i class="fa-solid fa-chart-line text-xl text-blue-400"></i><span>Analytics</span></a></li><li><a href="settings.php" class="nav-link active d-flex align-items-center gap-3 px-4 py-3 rounded-xl"><i class="fa-solid fa-gear text-xl text-orange-400"></i><span>Paramètres</span></a></li></ul></div><div class="p-6 border-t border-cyan-400/20 mt-auto"><a href="?logout=1" class="d-flex align-items-center gap-3 text-red-400 hover:text-red-300 transition-colors px-4 py-3"><i class="fa-solid fa-power-off"></i><span>DÉCONNEXION</span></a></div></nav>
<main class="main-content"><header class="glass-panel mx-4 mt-4 p-6 flex items-center justify-between"><div><h2 class="text-3xl font-bold title-font text-gradient"><?=$pageTitle?></h2><p class="text-slate-400 text-sm mt-1"><?=$pageDescription?></p></div></header><div class="p-6">
<div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
<div class="setting-card"><h3 class="text-xl font-bold title-font mb-6 text-cyan-300"><i class="fa-solid fa-user me-2"></i>Profil</h3><div class="space-y-4"><div><label class="text-slate-400 text-sm">Email</label><p class="text-cyan-300 font-medium"><?=htmlspecialchars($_SESSION['email'])?></p></div><div><label class="text-slate-400 text-sm">ID Utilisateur</label><p class="text-slate-300"><?=$_SESSION['user_id']?></p></div></div></div>
<div class="setting-card"><h3 class="text-xl font-bold title-font mb-6 text-purple-300"><i class="fa-solid fa-database me-2"></i>Données</h3><div class="space-y-4"><button onclick="exportData()" class="w-full btn-neon py-3 rounded-xl"><i class="fa-solid fa-download me-2"></i>Exporter mes données</button><button onclick="clearChat()" class="w-full px-6 py-3 rounded-xl border border-red-500/50 text-red-300 hover:bg-red-500/20"><i class="fa-solid fa-trash me-2"></i>Effacer l'historique</button></div></div>
<div class="setting-card lg:col-span-2"><h3 class="text-xl font-bold title-font mb-6 text-green-300"><i class="fa-solid fa-circle-info me-2"></i>À propos</h3><div class="grid grid-cols-1 md:grid-cols-3 gap-4"><div class="text-center p-4 bg-black/30 rounded-xl"><div class="text-3xl font-bold text-cyan-400">v7.0</div><div class="text-slate-400 text-sm">Version</div></div><div class="text-center p-4 bg-black/30 rounded-xl"><div class="text-3xl font-bold text-purple-400">Ultima</div><div class="text-slate-400 text-sm">Édition</div></div><div class="text-center p-4 bg-black/30 rounded-xl"><div class="text-3xl font-bold text-green-400">2025</div><div class="text-slate-400 text-sm">Année</div></div></div><p class="text-slate-400 text-sm mt-6">NEXUS Ultima est un portail d'intelligence artificielle évolutive avec analyse neuro-psychologique en temps réel et auto-renforcement adaptatif.</p></div>
</div>
</div></main>
<script>
async function exportData(){const res=await fetch('api.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'action=get_stats'});const data=await res.json();const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='nexus-data-'+new Date().toISOString().split('T')[0]+'.json';a.click();}
async function clearChat(){if(confirm('Êtes-vous sûr de vouloir effacer tout l\'historique ? Cette action est irréversible.')){alert('Fonctionnalité disponible prochainement.');}}
</script></body></html>
